# (Optional) Creates a gem cache data volume
gems-2.3.1:
  image: busybox
  volumes:
    - /data/db
  command: /bin/true
web:
  build: .
  dockerfile: Dockerfile-dev
  command: ./script/start.sh
  env_file: .env.development
  # Mounts your host directory as the application, for live editing
  volumes:
    - .:/app
  # (Optional) Attaches gem cache data volume
  volumes_from:
    - gems-2.3.1
  ports:
    - "80:80"